### PR TITLE
Add google collab/binder links

### PR DESCRIPTION
**Pull request by chris-rands**
@BioGeek does this look correct?

### CODE REVIEW

**Comment by BioGeek** [comment]
The Colab link gives me the following modal:

image

I think that is because you are linking to the notebook file on your personal Google drive? You can adapt the link to point to the publicly accessible Github file like this: 

https://colab.research.google.com/github/chris-rands/biopython-coronavirus/blob/master/biopython-coronavirus-notebook.ipynb

The Binder link can be slightly improved by instructing it to open the notebook directly:

https://mybinder.org/v2/gh/chris-rands/biopython-coronavirus/master?filepath=biopython-coronavirus-notebook.ipynb

So the button becomes:

[Binder](https://mybinder.org/v2/gh/chris-rands/biopython-coronavirus/master?filepath=biopython-coronavirus-notebook.ipynb)

**Comment by chris-rands** [comment]
Thank you, better now?

**Comment by BioGeek** [comment]
The Binder link now works as expected. But for the Google Colab link we get an import error because BioPython is not installed by default (and Google Colab doesn't look at the environment.yml file). So I would add a conditional before the imports that first tries to import to import a module that only exists in Colab and if so also installs BioPython.

This code cell shouldn't have any effect when run on mybinder.org.

```
try:
  import google.colab
  # We're running this notebook in Google Colab, so first install BioPython
  !pip install biopython==1.76
except:
  pass
```

image

**Comment by chris-rands** [comment]
Thanks, that was careless of me (I added this on my local google drive copy before), added it to the repo now via https://github.com/chris-rands/biopython-coronavirus/commit/435c6e0e0483031933905786cee219c65c6984fb. Okay now?

**Comment by BioGeek** [comment]
Yes, this looks good now.

A final tiny nitpick. Your commit [435c6e0 ](https://github.com/chris-rands/biopython-coronavirus/commit/435c6e0e0483031933905786cee219c65c6984fb) also includes updated values for the `execution_count` metadata. If you don't want these to clutter up your commit you can adapt a [script like this](https://gist.github.com/autodrive/cb05134b68205e4b94335dd67fe16023) to reset them before committing the notebook (but I would suggest to keep the outputs), or use [nbdime](https://nbdime.readthedocs.io/en/latest/index.html) and configure it to [ignore `execution_count`](https://nbdime.readthedocs.io/en/latest/config.html#configuring-ignores).

**Comment by chris-rands** [comment]
Great, thanks for your help!

Yes, I deliberately included the full output here, since the Notebook is small and some users may just view it. I have used [nbstripout](https://github.com/kynan/nbstripout) (and nbdime) for other projects

**Comment by chris-rands** [comment]
@BioGeek  Would you like to be named as a contributed at the bottom of the README?

e.g.

# Contributors
- [Chris Rands](https://github.com/chris-rands)
- [Jeroen Van Goey](https://github.com/BioGeek)

**Comment by BioGeek** [comment]
That is kind of you to suggest that, but you did the hard work of writing the notebook itself. I'm glad that I could be of assistance but no need to specifically mention me as contributor.

**Pull request merged**
